### ISSUE TITLE
overlap with other package

### ISSUE THREAD

**Issue by stanleyjs** [milescsmith/pyalra#2]
Hello Miles,

I am just curious - how does your implementation diverge from this previous implementation of alra for python?
https://github.com/pavlin-policar/ALRA/tree/master

Jay

**Comment by milescsmith** [comment]
Huh, I swear I searched to see if there was a Python implementation but didn't find one.

It looks to me like there are some minor differences in the way we went about translating from R to Python, but biggest that stands out is that I'm using [`scipy.randomized_pca`](https://github.com/milescsmith/pyalra/blob/7fd26f13d0a366ef48b5c77f477812de0e20d09b/src/pyalra/alra.py#L40), while the pavlin-policar/ALRA version is using [`fbpca.pca`](https://github.com/pavlin-policar/ALRA/blob/fab8d7661bf2a2179b40e68fb4f022015c700252/ALRA/ALRA.py#L21), which appears to be abandoned.  Other than that, it looks like it mostly comes down to updated dependencies.
